### ISSUE TITLE
Doc Suggestion

### ISSUE THREAD

**Issue by raindog308** [handyman5/poodledo#8]
Coming into this module cold, a couple points.

First, if you "python setup.py install" I think the example is actually "import poodledo.apiclient", right?

Second, I couldn't find any info on what should be in tdclirc or what its format is - ConfigParser format?  What sections?  What fields?  Dug it out of cli.py but you might want to document it.

Keep up the good work!

**Comment by raindog308** [comment]
Update: er, thought I dug it out but apparently not right.  My tdclirc in ~/.tdcli/tdclirc is:

[application]
id = <my app id from TD site>
token = <my token from TD site>

[config]
username = someone@example.com
password = MySuperSecretPassword

But this:

#!/usr/bin/python

import poodledo
from poodledo.apiclient import ApiClient
c = ApiClient()
c.authenticate('someone@example.com',MySuperSecretPassword')

Gives:

Traceback (most recent call last):
  File "/app/backup_toodledo/backup_toodledo.py", line 6, in <module>
    c.authenticate('someone@example.com',MySuperSecretPassword')
  File "/usr/lib/python2.6/site-packages/poodledo-0.2-py2.6.egg/poodledo/apiclient.py", line 180, in authenticate
    self._userid = bool(self._userid) and self._userid or self.getUserid(email, passwd)
  File "/usr/lib/python2.6/site-packages/poodledo-0.2-py2.6.egg/poodledo/apiclient.py", line 198, in getUserid
    sig=md5(email + self.application_token).hexdigest(),
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by yardern** [comment]
Have you ever got it working please?
